# Generated by Django 4.2 on 2023-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menuapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="tag",
        ),
        migrations.AddField(
            model_name="menu",
            name="type",
            field=models.CharField(
                choices=[
                    ("breakfast", "breakfast"),
                    ("launch", "launch"),
                    ("dinner", "dinner"),
                ],
                default="breakfast",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
