# Generated by Django 4.2 on 2023-07-11 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("date", models.DateTimeField()),
                ("people", models.PositiveIntegerField()),
                ("message", models.TextField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("lavozim", models.CharField(max_length=300)),
                (
                    "social_facebook",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "social_youtube",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "social_instagram",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("image", models.ImageField(upload_to="team_images")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
